In [1]:
#import libraries
!pip install kaggle
import kaggle

Collecting kaggle
  Downloading kaggle-1.6.14.tar.gz (82 kB)
     ---------------------------------------- 0.0/82.1 kB ? eta -:--:--
     ---- ----------------------------------- 10.2/82.1 kB ? eta -:--:--
     --------- ---------------------------- 20.5/82.1 kB 217.9 kB/s eta 0:00:01
     --------- ---------------------------- 20.5/82.1 kB 217.9 kB/s eta 0:00:01
     -------------- ----------------------- 30.7/82.1 kB 145.2 kB/s eta 0:00:01
     ----------------------- -------------- 51.2/82.1 kB 201.8 kB/s eta 0:00:01
     -------------------------------------  81.9/82.1 kB 269.5 kB/s eta 0:00:01
     -------------------------------------  81.9/82.1 kB 269.5 kB/s eta 0:00:01
     -------------------------------------- 82.1/82.1 kB 191.6 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six>=1.10 in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from kaggle) (2.9.0)
Requirement already satisfied: requests in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from kaggle) (2.32.3)
Collecting tqdm (from kaggle)
  Downloading tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ----------------------------------- ---- 51.2/57.6 kB 1.3 MB/s eta 0:00:01
     ----------------------------------- ---- 51.2/57.6 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 57.6/57.6 kB 434.1 kB/s eta 0:00:00
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: urllib3 in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from kaggle) (2.2.1)
Requirement already satisfied: bleach in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from bleach->kaggle) (0.5.1)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: colorama in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading tqdm-4.66.4-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.3 kB ? eta -:--:--
   ------------------------------------ --- 71.7/78.3 kB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 71.7/78.3 kB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 71.7/78.3 kB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 71.7/78.3 kB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 78.3/78.3 kB 310.7 kB/s eta 0:00:00
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.2 kB ? eta -:--:--
   ------------------------------------ --- 71.7/78.2 kB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 71.7/78.2 kB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 78.2/78.2 kB 730.3 kB/s eta 0:00:00
Building wheels for collected packages: kaggle
  Building wheel for kaggle (setup.py): started
  Building wheel for kaggle (setup.py): finished with status 'done'
  Created wheel for kaggle: filename=kaggle-1.6.14-py3-none-any.whl size=105128 sha256=3d3e391fb87c3390e7ce4e11e4c176d64c5403654d2a289dbebb2f2e7c83efd0
  Stored in directory: c:\users\rfare\appdata\local\pip\cache\wheels\89\bc\52\0d140fc172783e1e72e3af4dfc13015dc154527fafb95e65cd
Successfully built kaggle
Installing collected packages: text-unidecode, tqdm, python-slugify, kaggle
Successfully installed kaggle-1.6.14 python-slugify-8.0.4 text-unidecode-1.3 tqdm-4.66.4

In [2]:
#Download dataset using kaggle api
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\rfare\miniconda3\envs\python-for-data-analysis\Retail Orders SQL + Python Project

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 236kB/s]
100%|##########| 200k/200k [00:00<00:00, 236kB/s]

In [4]:
#Extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [5]:
#Read data from the file and handle null values
import pandas as pd
df = pd.read_csv('orders.csv')
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [6]:
df.isna().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [7]:
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [8]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [9]:
df = pd.read_csv('orders.csv', na_values=['Not Available', 'unknown'])
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [10]:
df.isna().sum()

Order Id            0
Order Date          0
Ship Mode           6
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [11]:
#rename column names to use a standard formate
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [12]:
df.columns = df.columns.str.lower()
df.columns

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [15]:
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [16]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [17]:
#Derive new columns discount, sale price, profit
df['discount'] = df['list_price'] * df['discount_percent'] * 0.01
df['sale_price'] = df['list_price'] - df['discount']
df['profit'] = df['sale_price'] - df['cost_price']
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [19]:
#convert the column data types to appropriate data types
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [21]:
df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d')
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [22]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [23]:
#Drop cost price, list price, discount percentage column
df.drop(columns=['cost_price', 'list_price', 'discount_percent'], inplace=True)
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [25]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.31-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rfare\miniconda3\envs\python-for-data-analysis\lib\site-packages (from sqlalchemy) (4.12.1)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Downloading greenlet-3.0.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Downloading SQLAlchemy-2.0.31-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 262.6 kB/s eta 0:00:08
    --------------------------------------- 0.0/2.1 MB 262.6 kB/s eta 0:00:08
   - -------------------------------------- 0.1/2.1 MB 328.2 kB/s eta 0:00:07
   - -------------------------------------- 0.1/2.1 MB 403.5 kB/s eta 0:00:05
   -- ------------------------------------- 0.1/2.1 MB 532.5 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/2.1 MB 689.2 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.1 MB 741.6 kB/s eta 0:00:03
   ------ --------------------------------- 0.3/2.1 MB 807.1 kB/s eta 0:00:03
   ------- -------------------------------- 0.4/2.1 MB 836.4 kB/s eta 0:00:03
   ---------- ----------------------------- 0.5/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.0 MB/s eta 0:00:02
   ----------- ---------------------------- 0.6/2.1 MB 680.2 kB/s eta 0:00:03
   ----------- ---------------------------- 0.6/2.1 MB 680.2 kB/s eta 0:00:03
   ----------- ---------------------------- 0.6/2.1 MB 680.2 kB/s eta 0:00:03
   ----------------- ---------------------- 0.9/2.1 MB 890.9 kB/s eta 0:00:02
   ------------------ --------------------- 1.0/2.1 MB 923.7 kB/s eta 0:00:02
   ------------------ --------------------- 1.0/2.1 MB 923.7 kB/s eta 0:00:02
   -------------------- ------------------- 1.1/2.1 MB 934.2 kB/s eta 0:00:02
   ---------------------- ----------------- 1.2/2.1 MB 1.0 MB/s eta 0:00:01
   ---------------------- ----------------- 1.2/2.1 MB 1.0 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 999.4 kB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------- ----------- 1.5/2.1 MB 1.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.5/2.1 MB 1.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.1 MB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 977.1 kB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 977.1 kB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 977.1 kB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 977.1 kB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 977.1 kB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 977.1 kB/s eta 0:00:01
   ---------------------------------------  2.0/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 988.6 kB/s eta 0:00:00
Downloading greenlet-3.0.3-cp312-cp312-win_amd64.whl (293 kB)
   ---------------------------------------- 0.0/293.6 kB ? eta -:--:--
   ----- --------------------------------- 41.0/293.6 kB 960.0 kB/s eta 0:00:01
   ------------ --------------------------- 92.2/293.6 kB 1.3 MB/s eta 0:00:01
   ------------------- -------------------- 143.4/293.6 kB 1.2 MB/s eta 0:00:01
   ----------------------------- ---------- 215.0/293.6 kB 1.3 MB/s eta 0:00:01
   ---------------------------------- ----- 256.0/293.6 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------  286.7/293.6 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------  286.7/293.6 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------  286.7/293.6 kB 1.2 MB/s eta 0:00:01
   -------------------------------------- 293.6/293.6 kB 787.2 kB/s eta 0:00:00
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.0.3 sqlalchemy-2.0.31

In [28]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl (69 kB)
   ---------------------------------------- 0.0/69.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----------------- ---------------------- 30.7/69.3 kB 186.2 kB/s eta 0:00:01
   ----------------------- ---------------- 41.0/69.3 kB 195.7 kB/s eta 0:00:01
   ----------------------------------- ---- 61.4/69.3 kB 272.3 kB/s eta 0:00:01
   ----------------------------------- ---- 61.4/69.3 kB 272.3 kB/s eta 0:00:01
   ---------------------------------------- 69.3/69.3 kB 198.7 kB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.1.0

In [29]:
#Load the data into SQL Server using replace option
import sqlalchemy as sal
engine = sal.create_engine('mssql://Rakib-Laptop/retail_orders?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn = engine.connect()

In [32]:
#Load the data into SQL server using append option
df.to_sql('retail_orders', con=conn, index=False, if_exists='append')

38